name: C bindings

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-c-bindings:
    name: Test C bindings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Make C test program
        run: make -C c_bindings BUILD_MODE=release

      - name: Run tests
        run: c_bindings/tests.elf

  release:
    name: Release ${{ matrix.crate-type }} for ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
        crate-type:
          - staticlib
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            os_name: windows
            runner: windows-latest
            architecture: x86
          - target: x86_64-pc-windows-msvc
            archive: zip
            os_name: windows
            runner: windows-latest
            architecture: x86
          - target: aarch64-pc-windows-msvc
            archive: zip
            os_name: windows
            runner: windows-latest
            architecture: aarch64
          - target: x86_64-apple-darwin
            archive: zip
            os_name: macos
            runner: macos-15-intel
            architecture: x86
          - target: aarch64-apple-darwin
            archive: zip
            os_name: macos
            runner: macos-latest
            architecture: aarch64
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
            os_name: linux
            runner: ubuntu-22.04
            architecture: x86
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
            os_name: linux
            runner: ubuntu-22.04
            architecture: x86
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz
            os_name: linux
            architecture: aarch64
            runner: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build lib
        run: cargo rustc --manifest-path lib/Cargo.toml --lib --features c_bindings --release --crate-type ${{ matrix.crate-type }} --target ${{ matrix.target }}

      - name: Install tree
        if: matrix.os_name == 'macos'
        run:
          brew install tree

      - name: Print built files
        if: matrix.os_name == 'linux' || matrix.os_name == 'macos'
        run: |
          tree target/${{ matrix.target }}/release

      - name: Print built files
        if: matrix.os_name == 'windows'
        run: |
          tree /f target/${{ matrix.target }}/release

      # Move versioned files to a new folder, this will contain the final release files
      - name: Move files for packaging
        run: |
          mkdir package
          mkdir package/lib
          mkdir package/include
          cp -r c_bindings/include/* package/include/
          cp LICENSE package/crunch64.LICENSEzip
          cp README.md package/crunch64.README.md

      # Move the built library.
      # This is a two step thing because windows is silly.
      - name: Move lib for packaging (unix)
        if: matrix.os_name == 'linux' || matrix.os_name == 'macos'
        run: |
          cp target/${{ matrix.target }}/release/libcrunch64.a package/lib/
          tree package

      - name: Move lib for packaging (windows)
        if: matrix.os_name == 'windows'
        run: |
          cp target/${{ matrix.target }}/release/crunch64.lib package/lib/
          tree /f package

      # Compress the package files
      # Two steps because windows silly
      - name: Package .tar.gz
        if: matrix.archive == 'tar.gz'
        run: |
          cd package && tar -czf ../crunch64-${{ matrix.crate-type }}-${{ matrix.target }}.tar.gz *

      - name: Package .zip
        if: matrix.archive == 'zip' && matrix.os_name == 'macos'
        run: |
          cd package && zip -r ../crunch64-${{ matrix.crate-type }}-${{ matrix.target }}.zip *

      - name: Package .zip
        if: matrix.archive == 'zip' && matrix.os_name == 'windows'
        run: |
          cd package; Compress-Archive -Path * -DestinationPath ../crunch64-${{ matrix.crate-type }}-${{ matrix.target }}.zip

      # Upload the artifact, useful for inspecting the artifacts
      - name: Upload ${{ matrix.archive }} archive
        uses: actions/upload-artifact@main
        with:
          name: crunch64-${{ matrix.crate-type }}-${{ matrix.target }}
          path: |
            crunch64-${{ matrix.crate-type }}-${{ matrix.target }}.${{ matrix.archive }}
          if-no-files-found: error

      # Build and run the archives. Multi step because each os/arch combo is weird
      - name: Test built archive (x86, unix like)
        if: (matrix.os_name == 'linux' && matrix.architecture == 'x86') || matrix.os_name == 'macos' || matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          cc -I c_bindings/include/ c_bindings/tests.c -L package/lib/ -l crunch64 -o tests.elf
          ./tests.elf

      - name: Setup qemu
        uses: docker/setup-qemu-action@v4
        if: matrix.os_name == 'linux' && matrix.architecture == 'aarch64'

      - name: Test built archive (aarch64 linux)
        if: matrix.os_name == 'linux' && matrix.architecture == 'aarch64'
        run: |
          docker run --platform linux/arm64 --rm -v ${{ github.workspace }}:/work -w /work gcc:latest \
          sh -c "cc -I c_bindings/include/ c_bindings/tests.c -L package/lib/ -l crunch64 -o tests.elf && ./tests.elf"

      - name: Test built archive (x86 msvc)
        if: (matrix.os_name == 'windows' && matrix.architecture == 'x86') && matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          cl /I c_bindings/include/ c_bindings/tests.c package/lib/crunch64.lib /Fe:tests.exe
          tests.exe

      # We don't have a way to build and run aarch64 windows binaries on GHA :c

      # Actually publish the built files to github releases
      - name: Publish ${{ matrix.archive }} release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: crunch64-${{ matrix.crate-type }}-${{ matrix.target }}.${{ matrix.archive }}
