name: Test Rust code

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all -- -D warnings

  macos-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --all-features

  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --all-features

  windows-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --all-features
